version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
- package-ecosystem: "github-actions"
  directory: "/" # checks in .github/workflows
  schedule:
    interval: daily
