on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
name: Build, Lint, Test, and Upload Codecov
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10.*]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: autopep8
      if: matrix.python-version == 3.8
      id: autopep8
      uses: peter-evans/autopep8@v1
      with:
        args: --exit-code --recursive --global-config .pycodestyle --in-place .
    - name: Set autopep8 branch name
      if: matrix.python-version == 3.8
      id: autopep8vars
      run: echo ::set-output name=branch-name::"autopep8-patches/${{ github.head_ref }}"
    - name: Create Pull Request if autopep8 found something
      if: matrix.python-version == 3.8 && steps.autopep8.outputs.exit-code == 2
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: autopep8 action fixes
        title: Fixes by autopep8 action
        body: This is an auto-generated PR with fixes by autopep8.
        labels: autopep8, automated pr
        branch: ${{ steps.autopep8vars.outputs.branch-name }}
    - name: Pep8 Style Checker
      run: |
        python -m pip install --upgrade pip
        pip install pycodestyle
        pycodestyle --config=.pycodestyle .
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pycodestyle pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest and calculate coverage
      run: |
        python -m pytest --cov=./benfords_law_utils/ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      if: matrix.python-version == 3.8
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
